### ISSUE TITLE
Replace moment

### ISSUE THREAD

**Issue by nainardev** [rmuif/web#441]
moment is **66 kB** (https://bundlephobia.com/result?p=moment@2.24.0)

use any other lighter alternatives
 - dayjs (2.8 kB)
 - date-fns (16.9 kB)
 - luxon (20 kB)

source: https://github.com/you-dont-need/You-Dont-Need-Momentjs

**Comment by phoqe** [comment]
I want to do this but am kind of blocked at the moment due to not knowing what to do with the security rating metric, i.e. if I want to keep it or not and what to replace the UI with, but I agree with you. Because the code for calculating the security rating is pretty garbage at the moment, it’s a non-sensical metric that only takes into account the user’s password and when they changed it last so that’ll need some work.

**Comment by nainardev** [comment]
What's preventing you from replacing `moment`?

**Comment by phoqe** [comment]
Will not replace moment in the foreseeable future. I like working with moment and I think others do as well.

**Comment by nainardev** [comment]
But it's huge
