### ISSUE TITLE
Links - work but need to refresh the page to get them to load

### ISSUE THREAD

**Issue by MincePie** [rmuif/web#642]
## Description

Wondering if anyone else is having an issue with new pages added to the structure. For me, the links update the url with the correct link name, but after the first link correctly loads the new page, each subsequent link clicked updates the url for the new page, but the page only loads after I refresh the browser.

## Reproduction
Errors in the console (for chrome only) are:

﻿
www.google-analytics.com/analytics.js:1 Failed to load resource: net::ERR_UNSAFE_REDIRECT
js.driftt.com/includ…0/3ut362ewn33w.js:1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
www.googletagmanager…ag/js?l=dataLayer:1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
﻿
​This is happening in firefox, chrome and safari - but the above errors are only being reported in chrome.

I'm not sure if these errors are linked to the problem.

Thank you

**Comment by phoqe** [comment]
Hello, can you provide some code to your repro? Thank you.

**Comment by WalissonRodrigo** [comment]
I may be mistaken but with me when this error occurs ERR_BLOCKED_BY_CLIENT is usually some browser extension that is causing this error. Ad blockers such as uBlock, uBlockOrigin or extensions that interpret scripts like MeddleMonkey, Tampermonkey and many other possible extensions can cause this error.

I recommend disabling all extensions and testing to see which one is causing the error.

There is a bug that I have not tested if it was resolved the first time you access the page because after it was authenticated it was not possible to load the authenticated data without updating the page, after the first access you can register, login and access the pages normally. I believe it is something in the cache because after updating the page you can use it normally.

**Comment by MincePie** [comment]
hmm - thanks for the insight.

This is happening on public pages that are linked on the landing page (no
auth required).

Other people are reporting the same links problem (they can only view the
linked page on refresh). I'll keep trying to solve it and share the
findings - if I discover them. This is happening on every browser, so I'm
not sure its cache related.

**Comment by phoqe** [comment]
Is this issue happening on the `demo` or `dev` version of RMUIF?
